"use client";
import { useEffect, useState } from "react";
import { Check, EyeOff, Flag, Star } from "lucide-react";
import { AdminBadge, AdminCard, AdminEmpty, AdminPage, AdminPageIntro, AdminRefreshButton } from "./AdminUi";

type Review={databaseId:number;content:string;rating:number;date:string;status:string;moderationState:string;userName:string;userEmail:string;productId:number;productName:string};
const STATES: Record<string,string>={pending:"در انتظار بررسی",published:"منتشرشده",flagged:"علامت‌گذاری‌شده",hidden:"مخفی"};

export default function AdminReviewsClient({initial}:{initial?:{nodes:Review[];pageInfo:{hasNextPage:boolean;endCursor:string|null}}}){
 const empty={nodes:[],pageInfo:{hasNextPage:false,endCursor:null}};const[data,setData]=useState(initial??empty),[state,setState]=useState("pending"),[loading,setLoading]=useState(!initial);
 useEffect(()=>{if(!initial)void load()},[]);
 const load=async(after?:string|null)=>{setLoading(true);try{const q=new URLSearchParams({state});if(after)q.set("after",after);const r=await fetch(`/api/admin/reviews?${q}`,{cache:"no-store"});if(r.ok)setData(await r.json())}finally{setLoading(false)}};
 const action=async(id:number,a:string)=>{setLoading(true);try{await fetch("/api/admin/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"moderate",reviewId:id,moderationAction:a})});await load()}finally{setLoading(false)}};
 return <AdminPage><AdminPageIntro eyebrow="عملیات" title="دیدگاه‌ها" description="صف moderation را کوتاه نگه دار و فقط موارد لازم را بررسی کن." action={<AdminRefreshButton onClick={()=>void load()} loading={loading}/>}/>
  <AdminCard className="mb-4 p-3"><div className="grid gap-2 sm:grid-cols-[1fr_110px]"><select value={state} onChange={e=>setState(e.target.value)} className="w-full min-h-10 rounded-[5px] border border-brand-surface_hover bg-brand-bg px-3 text-xs text-white outline-none placeholder:text-brand-m_khonsa focus:border-brand-blue focus:ring-2 focus:ring-brand-blue/20"><option value="pending">در انتظار بررسی</option><option value="published">منتشرشده</option><option value="flagged">علامت‌گذاری‌شده</option><option value="hidden">مخفی</option></select><button onClick={()=>void load()} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 bg-brand-blue text-white hover:brightness-110">اعمال</button></div></AdminCard>
  <div className="grid gap-3">{data.nodes.map(r=><AdminCard key={r.databaseId} className="p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div className="min-w-0"><div className="truncate text-sm font-black text-white">{r.productName||"محصول"}</div><div className="mt-1 flex flex-wrap items-center gap-2 text-[10px] text-brand-m_khonsa"><span>{r.userName||"کاربر"}</span><span>#{r.databaseId}</span><span className="inline-flex items-center gap-1 text-brand-zard"><Star size={11} fill="currentColor"/>{r.rating}/5</span><span>{STATES[state]??state}</span></div></div><div className="text-[9px] text-brand-m_khonsa" dir="ltr">{r.date?new Date(r.date).toLocaleString("fa-IR"):"—"}</div></div><div className="mt-3 rounded-[5px] bg-black/10 p-3 text-xs leading-6 text-white whitespace-pre-wrap">{r.content}</div><div className="mt-3 flex flex-wrap gap-2">{state!=="published"&&<button onClick={()=>void action(r.databaseId,"approve")} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 bg-brand-blue text-white hover:brightness-110 h-9 min-h-0 text-[10px]"><Check size={13}/> تأیید</button>}{state!=="hidden"&&<button onClick={()=>void action(r.databaseId,"hide")} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 border border-brand-surface_hover bg-brand-surface_hover/60 text-white hover:bg-brand-surface_hover h-9 min-h-0 text-[10px]"><EyeOff size={13}/> مخفی</button>}{state!=="flagged"&&<button onClick={()=>void action(r.databaseId,"flag")} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 h-9 min-h-0 border border-red-400/20 bg-red-500/5 text-[10px] font-black text-red-300"><Flag size={13}/> علامت‌گذاری</button>}</div></AdminCard>)}{data.nodes.length===0&&<AdminEmpty title="موردی در این صف وجود ندارد."/>}</div>
  {data.pageInfo.hasNextPage&&<div className="mt-4 flex justify-center"><button onClick={()=>void load(data.pageInfo.endCursor)} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 border border-brand-surface_hover bg-brand-surface_hover/60 text-white hover:bg-brand-surface_hover">صفحه بعد</button></div>}
 </AdminPage>
}
