"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, MessageSquare, StickyNote, UserCheck } from "lucide-react";
import { useAdminContext } from "./AdminContext";

const TICKET_STATUS_LABELS: Record<string,string> = { open:"باز", claimed:"در اختیار ادمین", waiting_user:"در انتظار کاربر", waiting_staff:"در انتظار پشتیبانی", resolved:"حل‌شده", closed:"بسته‌شده" };
const TICKET_PRIORITY_LABELS: Record<string,string> = { low:"کم", normal:"عادی", high:"زیاد", urgent:"فوری" };
type Detail={ticket:{databaseId:number;title:string;date:string;status:string;priority:string;customerId:number|null;customerName:string;customerEmail:string;linkedOrderId:number|null;assigneeId:number|null;assigneeName:string|null;claimExpiresAt:string|null};replies:Array<any>;events:Array<any>;internalNotes:Array<any>};
export default function AdminTicketDetail({data:initialData,id}:{data?:Detail;id:number}){
 const {permissions}=useAdminContext();
 const [data,setData]=useState<Detail|null>(initialData ?? null),[reply,setReply]=useState(""),[note,setNote]=useState(""),[loading,setLoading]=useState(!initialData),[actionLoading,setActionLoading]=useState(false),[status,setStatus]=useState(initialData?.ticket.status ?? "open"),[staff,setStaff]=useState<Array<{databaseId:number;name:string;email:string}>>([]),[assignee,setAssignee]=useState(initialData?.ticket.assigneeId?String(initialData.ticket.assigneeId):""),[error,setError]=useState("");
 useEffect(()=>{if(initialData)return;fetch(`/api/admin/tickets/${id}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error||"تیکت یافت نشد");setData(d);setStatus(d.ticket.status);setAssignee(d.ticket.assigneeId?String(d.ticket.assigneeId):"")}).catch(e=>setError(e instanceof Error?e.message:"خطا در دریافت تیکت")).finally(()=>setLoading(false));},[id,initialData]);
 useEffect(()=>{if(!permissions.includes("tickets.write"))return;fetch("/api/admin/tickets?staff=1",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setStaff(d?.staff||[])).catch(()=>{});},[permissions]);
 const post=async(body:any)=>{const r=await fetch("/api/admin/tickets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error();return r.json()};
 const reload=async()=>{if(!data)return;const r=await fetch(`/api/admin/tickets/${data.ticket.databaseId}`,{cache:"no-store"});if(!r.ok)return;const d=await r.json();setData(d);setStatus(d.ticket.status);setAssignee(d.ticket.assigneeId?String(d.ticket.assigneeId):"")};
 const act=async(body:any)=>{setActionLoading(true);try{await post(body);await reload()}finally{setActionLoading(false)}};
 return <div className="flex flex-col gap-4"><Link href="/admin/tickets" className="inline-flex items-center gap-2 text-xs font-bold text-brand-m_khonsa"><ArrowRight size={15}/> بازگشت به تیکت‌ها</Link>{error&&<div className="bg-red-500/10 border border-red-500/20 text-red-400 text-xs p-4">{error}</div>}{!data?<div className="min-h-[260px] bg-brand-surface border border-brand-surface_hover flex items-center justify-center text-xs text-brand-m_khonsa">{loading?"تیکت در حال دریافت اطلاعات...":"تیکت پیدا نشد."}</div>:<div className="grid grid-cols-1 xl:grid-cols-[1.4fr_1fr] gap-4"><div className="space-y-4"><section className="bg-brand-surface border border-brand-surface_hover p-5"><div className="flex items-start justify-between gap-4"><div><h1 className="text-xl font-black text-white">{data.ticket.title}</h1><div className="text-[10px] text-brand-m_khonsa mt-1">#{data.ticket.databaseId} · {TICKET_PRIORITY_LABELS[data.ticket.priority] ?? data.ticket.priority}</div></div>{permissions.includes("tickets.claim")&&<button onClick={()=>act({action:"claim",ticketId:data.ticket.databaseId})} disabled={actionLoading} className="inline-flex items-center gap-2 px-4 py-2.5 bg-brand-blue text-white text-xs font-black"><UserCheck size={14}/> دریافت مسئولیت</button>}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4"><Stat label="وضعیت" value={TICKET_STATUS_LABELS[data.ticket.status] ?? data.ticket.status}/><Stat label="مشتری" value={data.ticket.customerName||"—"}/><Stat label="مسئول" value={data.ticket.assigneeName||"—"}/><Stat label="سفارش" value={data.ticket.linkedOrderId?`#${data.ticket.linkedOrderId}`:"—"}/></div></section>
 <section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white mb-3 flex items-center gap-2"><MessageSquare size={16}/> گفتگو</h2><div className="space-y-3 max-h-[520px] overflow-y-auto">{data.replies.map((r:any)=><div key={r.id} className={`border border-brand-surface_hover p-3 ${r.authorRole==="staff"?"bg-brand-blue/5":""}`}><div className="flex justify-between gap-3"><div className="text-xs font-black text-white">{r.authorName}</div><div className="text-[10px] text-brand-m_khonsa">{r.createdAt?new Date(r.createdAt).toLocaleString("fa-IR"):"—"}</div></div><div className="text-xs text-white whitespace-pre-wrap mt-2">{r.content}</div></div>)}{data.replies.length===0&&<div className="text-xs text-brand-m_khonsa">گفتگویی ثبت نشده است.</div>}</div>{permissions.includes("tickets.write")&&<div className="mt-4"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={4} placeholder="پاسخ به مشتری..." className="w-full bg-brand-bg border border-brand-surface_hover p-3 text-xs text-white outline-none"/><button onClick={async()=>{await act({action:"reply",ticketId:data.ticket.databaseId,content:reply});setReply("")}} disabled={actionLoading||!reply.trim()} className="mt-2 px-4 py-2.5 bg-brand-blue text-white text-xs font-black">ارسال پاسخ</button></div>}</section>
 <section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white mb-3 flex items-center gap-2"><StickyNote size={16}/> یادداشت‌های داخلی</h2><div className="space-y-2">{data.internalNotes.map((n:any)=><div key={n.id} className="border border-brand-surface_hover p-3"><div className="text-xs text-white whitespace-pre-wrap">{n.content}</div><div className="text-[10px] text-brand-m_khonsa mt-2">{n.adminName} · {n.createdAt?new Date(n.createdAt).toLocaleString("fa-IR"):"—"}</div></div>)}{data.internalNotes.length===0&&<div className="text-xs text-brand-m_khonsa">یادداشت داخلی وجود ندارد.</div>}</div>{permissions.includes("tickets.write")&&<div className="mt-3"><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="یادداشت داخلی..." className="w-full bg-brand-bg border border-brand-surface_hover p-3 text-xs text-white outline-none"/><button onClick={async()=>{await act({action:"note",ticketId:data.ticket.databaseId,content:note});setNote("")}} disabled={actionLoading||!note.trim()} className="mt-2 px-4 py-2.5 bg-brand-surface_hover text-white text-xs font-black">ثبت یادداشت</button></div>}</section></div>
 <div className="space-y-4"><section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white">گردش تیکت</h2>{permissions.includes("tickets.write")&&<><select value={status} onChange={e=>setStatus(e.target.value)} className="mt-3 w-full bg-brand-bg border border-brand-surface_hover p-3 text-xs text-white">{[["open","باز"],["claimed","در اختیار ادمین"],["waiting_user","در انتظار کاربر"],["waiting_staff","در انتظار پشتیبانی"],["resolved","حل‌شده"],["closed","بسته‌شده"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button onClick={()=>act({action:"status",ticketId:data.ticket.databaseId,status})} disabled={actionLoading||status===data.ticket.status} className="mt-2 w-full px-4 py-2.5 bg-brand-blue text-white text-xs font-black">ذخیره وضعیت</button></>}</section><section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white">تغییر مسئول</h2>{permissions.includes("tickets.write")&&<><select value={assignee} onChange={e=>setAssignee(e.target.value)} className="mt-3 w-full bg-brand-bg border border-brand-surface_hover p-3 text-xs text-white"><option value="">انتخاب مدیر</option>{staff.map(s=><option key={s.databaseId} value={s.databaseId}>{s.name} · {s.email}</option>)}</select><button onClick={()=>assignee&&act({action:"reassign",ticketId:data.ticket.databaseId,adminUserId:Number(assignee)})} disabled={actionLoading||!assignee} className="mt-2 w-full px-4 py-2.5 bg-brand-surface_hover text-white text-xs font-black">تغییر مسئول</button></>}</section><section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white">اطلاعات مشتری</h2><div className="space-y-2 mt-3"><Row label="نام" value={data.ticket.customerName||"—"}/><Row label="ایمیل" value={data.ticket.customerEmail||"—"}/>{data.ticket.customerId&&<Link href={`/admin/customers/${data.ticket.customerId}`} className="text-brand-blue text-xs font-bold">پروفایل مشتری</Link>}{data.ticket.linkedOrderId&&<Link href={`/admin/orders/${data.ticket.linkedOrderId}`} className="block text-brand-blue text-xs font-bold">سفارش مرتبط #{data.ticket.linkedOrderId}</Link>}</div></section><section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white">تاریخچه</h2><div className="space-y-2 mt-3">{data.events.map((e:any)=><div key={e.id} className="border-b border-brand-surface_hover pb-2 last:border-0"><div className="text-[10px] text-brand-m_khonsa">{e.adminName} · {e.createdAt?new Date(e.createdAt).toLocaleString("fa-IR"):"—"}</div><div className="text-xs text-white mt-1">{e.type} {e.fromStatus&&`· ${TICKET_STATUS_LABELS[e.fromStatus] ?? e.fromStatus} ← ${TICKET_STATUS_LABELS[e.toStatus] ?? e.toStatus}`}</div></div>)}</div></section></div></div>}</div>
}
function Stat({label,value}:{label:string;value:string}){return <div className="border border-brand-surface_hover p-3"><div className="text-[10px] text-brand-m_khonsa">{label}</div><div className="text-xs font-black text-white mt-1">{value}</div></div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-2 border-b border-brand-surface_hover pb-2"><span className="text-[11px] text-brand-m_khonsa">{label}</span><span className="text-[11px] text-white font-bold break-all" dir="ltr">{value}</span></div>}
