"use client";
import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight } from "lucide-react";

export default function AdminCustomerDetail({data:initialData,id}:{data?:any;id:number}){
 const [data,setData]=useState(initialData??null),[loading,setLoading]=useState(!initialData),[error,setError]=useState("");
 useEffect(()=>{if(initialData)return;fetch(`/api/admin/customers/${id}`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error||"کاربر یافت نشد");setData(d)}).catch(e=>setError(e instanceof Error?e.message:"خطا در دریافت کاربر")).finally(()=>setLoading(false));},[id,initialData]);
 if(!data)return <div className="flex flex-col gap-4"><Link href="/admin/customers" className="inline-flex items-center gap-2 text-xs font-bold text-brand-m_khonsa"><ArrowRight size={15}/> بازگشت به مشتریان</Link>{error&&<div className="bg-red-500/10 border border-red-500/20 text-red-400 text-xs p-4">{error}</div>}<div className="min-h-[260px] bg-brand-surface border border-brand-surface_hover flex items-center justify-center text-xs text-brand-m_khonsa">{loading?"پروفایل در حال دریافت اطلاعات...":"کاربر پیدا نشد."}</div></div>;
 const c=data.customer;
 return <div className="flex flex-col gap-4"><Link href="/admin/customers" className="inline-flex items-center gap-2 text-xs font-bold text-brand-m_khonsa"><ArrowRight size={15}/> بازگشت به مشتریان</Link><div className="grid grid-cols-1 xl:grid-cols-[1fr_1.5fr] gap-4"><section className="bg-brand-surface border border-brand-surface_hover p-5"><h1 className="text-xl font-black text-white">{c.name||"—"}</h1><div className="text-[11px] text-brand-m_khonsa mt-1">مشتری #{c.databaseId}</div><div className="mt-5 space-y-2"><Row label="ایمیل" value={c.email}/><Row label="ثبت‌نام" value={c.registeredAt?new Date(c.registeredAt).toLocaleString("fa-IR"):"—"}/><Row label="نوع حساب" value={c.isStaff?"مدیر":"مشتری"}/><Row label="سفارش‌ها" value={String(c.ordersCount)}/><Row label="تیکت‌ها" value={String(c.ticketsCount)}/><Row label="دیدگاه‌ها" value={String(c.reviewsCount)}/></div><div className="mt-4 text-[10px] text-brand-m_khonsa">اطلاعات احراز هویت، تأیید بانکی و پروفایل بازی در این فاز عمداً بدون قرارداد مستقل به پنل تزریق نشده‌اند.</div></section><div className="space-y-4"><Collection title="سفارش‌های اخیر">{data.orders?.map((o:any)=><Link key={o.databaseId} href={`/admin/orders/${o.databaseId}`} className="flex items-center justify-between gap-3 border-b border-brand-surface_hover py-3"><div><div className="text-xs font-black text-white">#{o.orderNumber}</div><div className="text-[10px] text-brand-m_khonsa">{ORDER_STATUS_LABELS[o.status] ?? o.status} · {FULFILLMENT_STATUS_LABELS[o.fulfillmentStatus] ?? o.fulfillmentStatus}</div></div><span className="text-xs text-brand-blue">{o.total} {o.currency}</span></Link>)}{!data.orders?.length&&<Empty/>}</Collection><Collection title="تیکت‌های اخیر">{data.tickets?.map((t:any)=><Link key={t.databaseId} href={`/admin/tickets/${t.databaseId}`} className="block border-b border-brand-surface_hover py-3"><div className="text-xs font-black text-white">{t.title}</div><div className="text-[10px] text-brand-m_khonsa mt-1">{TICKET_STATUS_LABELS[t.status] ?? t.status} · #{t.databaseId}</div></Link>)}{!data.tickets?.length&&<Empty/>}</Collection><Collection title="دیدگاه‌های اخیر">{data.reviews?.map((r:any)=><div key={r.databaseId} className="border-b border-brand-surface_hover py-3"><div className="text-xs text-white">{r.productName||"محصول"}</div><div className="text-[10px] text-brand-m_khonsa mt-1">{r.rating}/5 · {r.approved?"منتشرشده":"در انتظار بررسی"}</div><div className="text-xs text-white mt-2 line-clamp-2">{r.content}</div></div>)}{!data.reviews?.length&&<Empty/>}</Collection></div></div></div>
}
const ORDER_STATUS_LABELS: Record<string,string> = { pending:"در انتظار", processing:"در حال پردازش", "on-hold":"در انتظار اقدام", completed:"تکمیل‌شده", cancelled:"لغوشده", refunded:"مستردشده", failed:"ناموفق" };
const FULFILLMENT_STATUS_LABELS: Record<string,string> = { pending:"در انتظار تکمیل", processing:"در حال تکمیل", partially_fulfilled:"تکمیل ناقص", fulfilled:"تکمیل‌شده", completed:"تکمیل کامل", cancelled:"لغوشده" };
const TICKET_STATUS_LABELS: Record<string,string> = { open:"باز", claimed:"در اختیار ادمین", waiting_user:"در انتظار کاربر", waiting_staff:"در انتظار پشتیبانی", resolved:"حل‌شده", closed:"بسته‌شده" };

function Collection({title,children}:{title:string;children:ReactNode}){return <section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white mb-2">{title}</h2>{children}</section>}
function Empty(){return <div className="text-xs text-brand-m_khonsa py-4">اطلاعاتی وجود ندارد.</div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-3 border-b border-brand-surface_hover pb-2"><span className="text-[11px] text-brand-m_khonsa">{label}</span><span className="text-[11px] text-white font-bold break-all" dir="ltr">{value}</span></div>}
