"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, MessageSquare, StickyNote, UserCheck } from "lucide-react";

type Detail={ticket:{databaseId:number;title:string;date:string;status:string;priority:string;customerId:number|null;customerName:string;customerEmail:string;linkedOrderId:number|null;assigneeId:number|null;assigneeName:string|null;claimExpiresAt:string|null};replies:Array<any>;events:Array<any>;internalNotes:Array<any>};
export default function AdminTicketDetail({data,permissions}:{data:Detail;permissions:string[]}){
 const [reply,setReply]=useState(""),[note,setNote]=useState(""),[loading,setLoading]=useState(false),[status,setStatus]=useState(data.ticket.status),[staff,setStaff]=useState<Array<{databaseId:number;name:string;email:string}>>([]),[assignee,setAssignee]=useState(data.ticket.assigneeId?String(data.ticket.assigneeId):"");
 useEffect(()=>{ if(!permissions.includes("tickets.write")) return; fetch("/api/admin/tickets?staff=1",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(d=>setStaff(d?.staff||[])).catch(()=>{}); },[permissions]);
 const post=async(body:any)=>{const r=await fetch("/api/admin/tickets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error();return r.json()};
 const act=async(body:any)=>{setLoading(true);try{await post(body);window.location.reload()}finally{setLoading(false)}};
 return <div className="flex flex-col gap-4"><Link href="/admin/tickets" className="inline-flex items-center gap-2 text-xs font-bold text-brand-m_khonsa"><ArrowRight size={15}/> Tickets</Link><div className="grid grid-cols-1 xl:grid-cols-[1.4fr_1fr] gap-4"><div className="space-y-4"><section className="bg-brand-surface border border-brand-surface_hover p-5"><div className="flex items-start justify-between gap-4"><div><h1 className="text-xl font-black text-white">{data.ticket.title}</h1><div className="text-[10px] text-brand-m_khonsa mt-1">#{data.ticket.databaseId} · {data.ticket.priority}</div></div>{permissions.includes("tickets.claim")&&<button onClick={()=>act({action:"claim",ticketId:data.ticket.databaseId})} disabled={loading} className="inline-flex items-center gap-2 px-4 py-2.5 bg-brand-blue text-white text-xs font-black"><UserCheck size={14}/> Claim</button>}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4"><Stat label="Status" value={data.ticket.status}/><Stat label="Customer" value={data.ticket.customerName||"—"}/><Stat label="Assignee" value={data.ticket.assigneeName||"—"}/><Stat label="Order" value={data.ticket.linkedOrderId?`#${data.ticket.linkedOrderId}`:"—"}/></div></section>
 <section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white mb-3 flex items-center gap-2"><MessageSquare size={16}/> Conversation</h2><div className="space-y-3 max-h-[520px] overflow-y-auto">{data.replies.map((r:any)=><div key={r.id} className={`border border-brand-surface_hover p-3 ${r.authorRole==="staff"?"bg-brand-blue/5":""}`}><div className="flex justify-between gap-3"><div className="text-xs font-black text-white">{r.authorName}</div><div className="text-[10px] text-brand-m_khonsa">{r.createdAt?new Date(r.createdAt).toLocaleString("fa-IR"):"—"}</div></div><div className="text-xs text-white whitespace-pre-wrap mt-2">{r.content}</div></div>)}{data.replies.length===0&&<div className="text-xs text-brand-m_khonsa">گفتگویی ثبت نشده است.</div>}</div>{permissions.includes("tickets.write")&&<div className="mt-4"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={4} placeholder="پاسخ به مشتری..." className="w-full bg-brand-bg border border-brand-surface_hover p-3 text-xs text-white outline-none"/><button onClick={()=>act({action:"reply",ticketId:data.ticket.databaseId,content:reply})} disabled={loading||!reply.trim()} className="mt-2 px-4 py-2.5 bg-brand-blue text-white text-xs font-black">ارسال پاسخ</button></div>}</section>
 <section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white mb-3 flex items-center gap-2"><StickyNote size={16}/> Internal Notes</h2><div className="space-y-2">{data.internalNotes.map((n:any)=><div key={n.id} className="border border-brand-surface_hover p-3"><div className="text-xs text-white whitespace-pre-wrap">{n.content}</div><div className="text-[10px] text-brand-m_khonsa mt-2">{n.adminName} · {n.createdAt?new Date(n.createdAt).toLocaleString("fa-IR"):"—"}</div></div>)}{data.internalNotes.length===0&&<div className="text-xs text-brand-m_khonsa">یادداشت داخلی وجود ندارد.</div>}</div>{permissions.includes("tickets.write")&&<div className="mt-3"><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="یادداشت داخلی..." className="w-full bg-brand-bg border border-brand-surface_hover p-3 text-xs text-white outline-none"/><button onClick={()=>act({action:"note",ticketId:data.ticket.databaseId,content:note})} disabled={loading||!note.trim()} className="mt-2 px-4 py-2.5 bg-brand-surface_hover text-white text-xs font-black">ثبت یادداشت</button></div>}</section></div>
 <div className="space-y-4"><section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white">Workflow</h2>{permissions.includes("tickets.write")&&<><select value={status} onChange={e=>setStatus(e.target.value)} className="mt-3 w-full bg-brand-bg border border-brand-surface_hover p-3 text-xs text-white">{["open","claimed","waiting_user","waiting_staff","resolved","closed"].map(s=><option key={s} value={s}>{s}</option>)}</select><button onClick={()=>act({action:"status",ticketId:data.ticket.databaseId,status})} disabled={loading||status===data.ticket.status} className="mt-2 w-full px-4 py-2.5 bg-brand-blue text-white text-xs font-black">ذخیره وضعیت</button></>}</section><section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white">Assignment</h2>{permissions.includes("tickets.write")&&<><select value={assignee} onChange={e=>setAssignee(e.target.value)} className="mt-3 w-full bg-brand-bg border border-brand-surface_hover p-3 text-xs text-white"><option value="">انتخاب ادمین</option>{staff.map(s=><option key={s.databaseId} value={s.databaseId}>{s.name} · {s.email}</option>)}</select><button onClick={()=>assignee&&act({action:"reassign",ticketId:data.ticket.databaseId,adminUserId:Number(assignee)})} disabled={loading||!assignee} className="mt-2 w-full px-4 py-2.5 bg-brand-surface_hover text-white text-xs font-black">تغییر مسئول</button></>}</section><section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white">Customer Context</h2><div className="space-y-2 mt-3"><Row label="Name" value={data.ticket.customerName||"—"}/><Row label="Email" value={data.ticket.customerEmail||"—"}/>{data.ticket.customerId&&<Link href={`/admin/customers/${data.ticket.customerId}`} className="text-brand-blue text-xs font-bold">پروفایل کاربر</Link>}{data.ticket.linkedOrderId&&<Link href={`/admin/orders/${data.ticket.linkedOrderId}`} className="block text-brand-blue text-xs font-bold">سفارش مرتبط #{data.ticket.linkedOrderId}</Link>}</div></section><section className="bg-brand-surface border border-brand-surface_hover p-5"><h2 className="text-sm font-black text-white">History</h2><div className="space-y-2 mt-3">{data.events.map((e:any)=><div key={e.id} className="border-b border-brand-surface_hover pb-2 last:border-0"><div className="text-[10px] text-brand-m_khonsa">{e.adminName} · {e.createdAt?new Date(e.createdAt).toLocaleString("fa-IR"):"—"}</div><div className="text-xs text-white mt-1">{e.type} {e.fromStatus&&`· ${e.fromStatus} → ${e.toStatus}`}</div></div>)}</div></section></div></div></div>
}
function Stat({label,value}:{label:string;value:string}){return <div className="border border-brand-surface_hover p-3"><div className="text-[10px] text-brand-m_khonsa">{label}</div><div className="text-xs font-black text-white mt-1">{value}</div></div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-2 border-b border-brand-surface_hover pb-2"><span className="text-[11px] text-brand-m_khonsa">{label}</span><span className="text-[11px] text-white font-bold break-all" dir="ltr">{value}</span></div>}
