"use client";
import Link from "next/link";
import { useState } from "react";
import { Eye, RefreshCw, Search, ChevronLeft } from "lucide-react";

type Ticket={databaseId:number;title:string;date:string;status:string;priority:string;customerName:string;customerEmail:string;linkedOrderId:number|null;assigneeName:string|null;claimExpiresAt:string|null};
export default function AdminTicketsClient({initial}:{initial:{nodes:Ticket[];pageInfo:{hasNextPage:boolean;endCursor:string|null}}}){
 const [data,setData]=useState(initial),[status,setStatus]=useState("open"),[search,setSearch]=useState(""),[loading,setLoading]=useState(false);
 const load=async(after?:string|null)=>{setLoading(true);try{const q=new URLSearchParams({status,search});if(after)q.set("after",after);const r=await fetch(`/api/admin/tickets?${q}`,{cache:"no-store"});if(r.ok)setData(await r.json())}finally{setLoading(false)}};
 return <div className="flex flex-col gap-4"><div className="flex items-end justify-between gap-3"><div><div className="text-[11px] uppercase tracking-[.18em] text-brand-blue font-black">Operations</div><h1 className="text-2xl font-black text-white mt-1">Tickets</h1><p className="text-xs text-brand-m_khonsa mt-2">Claim، پاسخ، یادداشت داخلی و lifecycle پشتیبانی.</p></div><button onClick={()=>load()} disabled={loading} className="inline-flex items-center gap-2 px-4 py-2.5 bg-brand-surface border border-brand-surface_hover text-xs font-bold text-white"><RefreshCw size={14} className={loading?"animate-spin":""}/> بروزرسانی</button></div>
 <div className="bg-brand-surface border border-brand-surface_hover p-3 flex flex-col md:flex-row gap-2"><div className="flex-1 flex items-center gap-2 border border-brand-surface_hover px-3"><Search size={15} className="text-brand-m_khonsa"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="عنوان / متن" className="w-full bg-transparent py-2.5 text-xs text-white outline-none"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="bg-brand-bg border border-brand-surface_hover px-3 py-2.5 text-xs text-white"><option value="open">open</option><option value="claimed">claimed</option><option value="waiting_user">waiting_user</option><option value="waiting_staff">waiting_staff</option><option value="resolved">resolved</option><option value="closed">closed</option><option value="all">all</option></select><button onClick={()=>load()} className="px-4 py-2.5 bg-brand-blue text-white text-xs font-black">اعمال</button></div>
 <div className="bg-brand-surface border border-brand-surface_hover overflow-x-auto"><table className="min-w-[950px] w-full text-right"><thead><tr className="border-b border-brand-surface_hover text-[10px] uppercase text-brand-m_khonsa"><th className="p-3">Ticket</th><th className="p-3">Customer</th><th className="p-3">Status</th><th className="p-3">Priority</th><th className="p-3">Assignee</th><th className="p-3">Order</th><th className="p-3">Date</th><th className="p-3"></th></tr></thead><tbody>{data.nodes.map(t=><tr key={t.databaseId} className="border-b border-brand-surface_hover last:border-0"><td className="p-3"><div className="text-sm font-black text-white">{t.title}</div><div className="text-[10px] text-brand-m_khonsa">#{t.databaseId}</div></td><td className="p-3"><div className="text-xs text-white">{t.customerName||"—"}</div><div className="text-[10px] text-brand-m_khonsa" dir="ltr">{t.customerEmail||"—"}</div></td><td className="p-3 text-xs text-white">{t.status}</td><td className="p-3 text-xs text-white">{t.priority}</td><td className="p-3 text-xs text-white">{t.assigneeName||"—"}</td><td className="p-3 text-xs text-white">{t.linkedOrderId?<Link href={`/admin/orders/${t.linkedOrderId}`} className="text-brand-blue">#{t.linkedOrderId}</Link>:"—"}</td><td className="p-3 text-[10px] text-brand-m_khonsa" dir="ltr">{t.date?new Date(t.date).toLocaleString("fa-IR"):"—"}</td><td className="p-3"><Link href={`/admin/tickets/${t.databaseId}`} className="inline-flex items-center gap-1 text-brand-blue text-xs font-black"><Eye size={14}/> جزئیات</Link></td></tr>)}</tbody></table>{data.nodes.length===0&&<div className="p-10 text-center text-xs text-brand-m_khonsa">تیکتی با این فیلتر پیدا نشد.</div>}</div>
 {data.pageInfo.hasNextPage&&<div className="flex justify-center"><button onClick={()=>load(data.pageInfo.endCursor)} disabled={loading} className="inline-flex items-center gap-2 border border-brand-surface_hover bg-brand-surface px-4 py-2.5 text-xs text-white"><ChevronLeft size={15}/> صفحه بعد</button></div>}
 </div>
}
