"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Eye, Search, ChevronLeft } from "lucide-react";
import { AdminBadge, AdminCard, AdminEmpty, AdminPage, AdminPageIntro, AdminRefreshButton } from "./AdminUi";

const STATUS: Record<string,string>={open:"باز",claimed:"در اختیار ادمین",waiting_user:"در انتظار کاربر",waiting_staff:"در انتظار پشتیبانی",resolved:"حل‌شده",closed:"بسته‌شده"};
const PRIORITY: Record<string,string>={low:"کم",normal:"عادی",high:"زیاد",urgent:"فوری"};
type Ticket={databaseId:number;title:string;date:string;status:string;priority:string;customerName:string;customerEmail:string;linkedOrderId:number|null;assigneeName:string|null;claimExpiresAt:string|null};

export default function AdminTicketsClient({initial}:{initial?:{nodes:Ticket[];pageInfo:{hasNextPage:boolean;endCursor:string|null}}}){
 const empty={nodes:[],pageInfo:{hasNextPage:false,endCursor:null}};const[data,setData]=useState(initial??empty),[status,setStatus]=useState("open"),[search,setSearch]=useState(""),[loading,setLoading]=useState(!initial);
 useEffect(()=>{if(!initial)void load()},[]);
 const load=async(after?:string|null)=>{setLoading(true);try{const q=new URLSearchParams({status,search});if(after)q.set("after",after);const r=await fetch(`/api/admin/tickets?${q}`,{cache:"no-store"});if(r.ok)setData(await r.json())}finally{setLoading(false)}};
 return <AdminPage>
  <AdminPageIntro eyebrow="پشتیبانی" title="تیکت‌ها" description="صف پشتیبانی را claim کن، پاسخ بده و وضعیت را جلو ببر." action={<AdminRefreshButton onClick={()=>void load()} loading={loading}/>}/>
  <AdminCard className="mb-4 p-3"><div className="grid gap-2 md:grid-cols-[1fr_180px_110px]"><label className="admin-search-wrap"><Search size={15} className="text-brand-m_khonsa"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()} placeholder="عنوان یا متن تیکت" className="admin-input border-0 bg-transparent px-0 shadow-none focus:shadow-none"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="admin-input"><option value="open">باز</option><option value="claimed">در اختیار ادمین</option><option value="waiting_user">در انتظار کاربر</option><option value="waiting_staff">در انتظار پشتیبانی</option><option value="resolved">حل‌شده</option><option value="closed">بسته‌شده</option><option value="all">همه</option></select><button onClick={()=>void load()} className="admin-button admin-button-primary">اعمال</button></div></AdminCard>
  <div className="admin-table-wrap desktop-only"><table className="admin-table"><thead><tr><th>تیکت</th><th>مشتری</th><th>وضعیت</th><th>اولویت</th><th>مسئول</th><th>سفارش</th><th>تاریخ</th><th/></tr></thead><tbody>{data.nodes.map(t=><tr key={t.databaseId}><td><div className="text-xs font-black text-white">{t.title}</div><div className="mt-1 text-[9px] text-brand-m_khonsa">#{t.databaseId}</div></td><td><div className="text-[10px] font-bold text-white">{t.customerName||"—"}</div><div className="mt-1 text-[9px] text-brand-m_khonsa" dir="ltr">{t.customerEmail||"—"}</div></td><td><AdminBadge tone={t.status==="resolved"||t.status==="closed"?"success":t.status==="open"?"warning":"info"}>{STATUS[t.status]??t.status}</AdminBadge></td><td><span className="text-[10px] text-white">{PRIORITY[t.priority]??t.priority}</span></td><td><span className="text-[10px] text-white">{t.assigneeName||"بدون مسئول"}</span></td><td>{t.linkedOrderId?<Link href={`/admin/orders/${t.linkedOrderId}`} className="text-[10px] text-brand-blue">#{t.linkedOrderId}</Link>:<span className="text-[10px] text-brand-m_khonsa">—</span>}</td><td><span className="text-[9px] text-brand-m_khonsa">{t.date?new Date(t.date).toLocaleDateString("fa-IR"):"—"}</span></td><td><Link href={`/admin/tickets/${t.databaseId}`} className="inline-flex items-center gap-1 text-[10px] font-black text-brand-blue"><Eye size={14}/> باز کردن</Link></td></tr>)}</tbody></table>{data.nodes.length===0&&<AdminEmpty title="تیکتی با این فیلتر پیدا نشد."/>}</div>
  <div className="mobile-only-card space-y-2">{data.nodes.map(t=><Link key={t.databaseId} href={`/admin/tickets/${t.databaseId}`} className="admin-card block p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-black text-white">{t.title}</div><div className="mt-1 text-[10px] text-brand-m_khonsa">{t.customerName||"—"} · #{t.databaseId}</div></div><AdminBadge tone={t.priority==="urgent"||t.priority==="high"?"danger":t.status==="open"?"warning":"info"}>{STATUS[t.status]??t.status}</AdminBadge></div><div className="mt-4 grid grid-cols-2 gap-3"><Mini label="اولویت" value={PRIORITY[t.priority]??t.priority}/><Mini label="مسئول" value={t.assigneeName||"بدون مسئول"}/><Mini label="سفارش" value={t.linkedOrderId?`#${t.linkedOrderId}`:"—"}/><Mini label="تاریخ" value={t.date?new Date(t.date).toLocaleDateString("fa-IR"):"—"}/></div></Link>)}{data.nodes.length===0&&<AdminEmpty title="تیکتی پیدا نشد."/>}</div>
  {data.pageInfo.hasNextPage&&<div className="mt-4 flex justify-center"><button onClick={()=>void load(data.pageInfo.endCursor)} disabled={loading} className="admin-button admin-button-muted"><ChevronLeft size={15}/> صفحه بعد</button></div>}
 </AdminPage>
}
function Mini({label,value}:{label:string;value:string}){return <div><div className="text-[9px] text-brand-m_khonsa">{label}</div><div className="mt-1 truncate text-[10px] font-bold text-white">{value}</div></div>}
