"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ChevronLeft, Eye, Search, Users } from "lucide-react";
import { AdminBadge, AdminCard, AdminEmpty, AdminPage, AdminPageIntro, AdminRefreshButton } from "./AdminUi";

type Customer={databaseId:number;name:string;email:string;registeredAt:string;isStaff:boolean;ordersCount:number;ticketsCount:number;reviewsCount:number};

export default function AdminCustomersClient({initial}:{initial?:{nodes:Customer[];pageInfo:{hasNextPage:boolean;endCursor:string|null}}}){
 const empty={nodes:[] as Customer[],pageInfo:{hasNextPage:false,endCursor:null}};
 const [data,setData]=useState(initial ?? empty),[search,setSearch]=useState(""),[loading,setLoading]=useState(!initial);
 const load=async(after?:string|null)=>{setLoading(true);try{const q=new URLSearchParams({search});if(after)q.set("after",after);const r=await fetch(`/api/admin/customers?${q}`,{cache:"no-store"});if(r.ok)setData(await r.json())}finally{setLoading(false)}};
 useEffect(()=>{if(!initial)void load();},[]);
 return <AdminPage>
  <AdminPageIntro eyebrow="حساب‌ها" title="مشتریان" description="پرونده عملیاتی مشتری و ارتباط آن با سفارش‌ها، تیکت‌ها و دیدگاه‌ها." action={<AdminRefreshButton onClick={()=>void load()} loading={loading}/>}/>
  <AdminCard className="mb-4 p-3"><div className="grid gap-2 md:grid-cols-[1fr_110px]"><label className="flex min-h-10 items-center gap-2 rounded-[5px] border border-brand-surface_hover bg-brand-bg px-3 focus-within:border-brand-blue focus-within:ring-2 focus-within:ring-brand-blue/20"><Search size={15} className="text-brand-m_khonsa"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()} placeholder="نام، ایمیل یا نام کاربری" className="w-full min-h-10 rounded-[5px] border border-brand-surface_hover bg-brand-bg px-3 text-xs text-white outline-none placeholder:text-brand-m_khonsa focus:border-brand-blue focus:ring-2 focus:ring-brand-blue/20 border-0 bg-transparent px-0 shadow-none focus:shadow-none"/></label><button onClick={()=>void load()} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 bg-brand-blue text-white hover:brightness-110">جستجو</button></div></AdminCard>

  <div className="overflow-hidden rounded-[5px] border border-white/[.06] bg-brand-surface hidden lg:block"><table className="w-full border-collapse text-right [&_th]:whitespace-nowrap [&_th]:border-b [&_th]:border-white/[.06] [&_th]:px-3.5 [&_th]:py-3 [&_th]:text-[9px] [&_th]:font-black [&_th]:text-brand-m_khonsa [&_td]:border-b [&_td]:border-white/[.06] [&_td]:px-3.5 [&_td]:py-3 [&_td]:align-middle [&_tr:last-child_td]:border-b-0 [&_tbody_tr]:transition-colors [&_tbody_tr:hover]:bg-white/[.02]"><thead><tr><th>مشتری</th><th>ایمیل</th><th>سفارش</th><th>تیکت</th><th>دیدگاه</th><th>ثبت‌نام</th><th/></tr></thead><tbody>{data.nodes.map(c=><tr key={c.databaseId}><td><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-[5px] bg-white/[.04] text-brand-m_khonsa"><Users size={15}/></span><div><div className="text-xs font-black text-white">{c.name||"—"}</div><div className="mt-1 text-[9px] text-brand-m_khonsa">#{c.databaseId} {c.isStaff&&<AdminBadge tone="info">کارمند</AdminBadge>}</div></div></div></td><td><span className="text-[10px] text-white" dir="ltr">{c.email}</span></td><td className="text-[11px] text-white">{c.ordersCount.toLocaleString("fa-IR")}</td><td className="text-[11px] text-white">{c.ticketsCount.toLocaleString("fa-IR")}</td><td className="text-[11px] text-white">{c.reviewsCount.toLocaleString("fa-IR")}</td><td><span className="text-[9px] text-brand-m_khonsa">{c.registeredAt?new Date(c.registeredAt).toLocaleDateString("fa-IR"):"—"}</span></td><td><Link href={`/admin/customers/${c.databaseId}`} className="inline-flex items-center gap-1 text-[10px] font-black text-brand-blue"><Eye size={14}/> پروفایل</Link></td></tr>)}</tbody></table>{data.nodes.length===0&&<AdminEmpty title="مشتری‌ای با این جستجو پیدا نشد."/>}</div>
  <div className="lg:hidden space-y-2">{data.nodes.map(c=><Link key={c.databaseId} href={`/admin/customers/${c.databaseId}`} className="rounded-[5px] border border-white/[.06] bg-brand-surface block p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-black text-white">{c.name||"بدون نام"}</div><div className="mt-1 text-[10px] text-brand-m_khonsa" dir="ltr">{c.email}</div></div>{c.isStaff&&<AdminBadge tone="info">کارمند</AdminBadge>}</div><div className="mt-4 grid grid-cols-3 gap-3"><Mini label="سفارش" value={c.ordersCount}/><Mini label="تیکت" value={c.ticketsCount}/><Mini label="دیدگاه" value={c.reviewsCount}/></div></Link>)}{data.nodes.length===0&&<AdminEmpty title="مشتری‌ای پیدا نشد."/>}</div>
  {data.pageInfo.hasNextPage&&<div className="mt-4 flex justify-center"><button onClick={()=>void load(data.pageInfo.endCursor)} disabled={loading} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-[5px] px-3 text-xs font-black transition disabled:pointer-events-none disabled:opacity-50 border border-brand-surface_hover bg-brand-surface_hover/60 text-white hover:bg-brand-surface_hover"><ChevronLeft size={15}/> صفحه بعد</button></div>}
 </AdminPage>
}
function Mini({label,value}:{label:string;value:number}){return <div><div className="text-[9px] text-brand-m_khonsa">{label}</div><div className="mt-1 text-xs font-black text-white">{value.toLocaleString("fa-IR")}</div></div>}
